---
title: "3-models"
author: "Rebekah Petroff"
date: "9/23/2021"
output: html_document
---

NOTE: the original processing file and model fitting file was written over somehow with another analysis...This is the replacement code to reflect the data in "3-modelFitting.html".


```{r setup, include=FALSE}
library(knitr)
knitr::opts_knit$set(root.dir = normalizePath("L:/MMIP EPIC/PFAS/PFAS_bs")) #set your wd
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, comment = NA) #dont include the code in your output, no warnings, no hashes before output
options(digits = 3)
library(tidyverse) #for dplyr and other tidyverse commands
library(gt) #pretty printing of tables
library(minfi)#forRG set
library(ENmix)#for surrogate var analysis
library(ChAMP)#forbatcheffects
library(missMethyl) #pathway analysis (for EPIC data, specifically)
library(limma) ##main package we are using for modeling
library(QCEWAS) #using this to calculate lambda
library(DMRcate) #for DMR (regional) analysis
library(Hmisc)#forimputing
```


```{r load data and rename}
load("./preprocess_output/beta_fornosex.rda")
load("./preprocess_output/finalpheno.rda")
load("./preprocess_output/annot_fornosex.rda")

beta <- betaXY
pheno <- orderedfinalgroup
annot <- annotXY

remove(betaXY, orderedfinalgroup, annotXY)
```


```{r imputing data race cat 3, echo=FALSE}
pheno$race3_imputed <- pheno$race_3cat #duplicate instead of writing over

#to imput, we #write our own sample based on the proportions that exist in our population. before using it on our data, we can test on a large imaginary sample population with no data, then replace just our missing values if that looks good
test <- sample(c(0,1,2), size=1000, prob = c((sum(which(pheno$race_3cat==0))/length(pheno$race_3cat)),
                                          (sum(which(pheno$race_3cat==1))/length(pheno$race_3cat)), 
                                          (sum(which(pheno$race_3cat==2))/length(pheno$race_3cat))), 
                                          replace = TRUE) 
print(test) #looks great!

pheno$race3_imputed <- ifelse(pheno$race3_imputed == 99, #if value ==99, then: 
                              #replace by a representative coin flip of our other proportion
                              sample(c(0,1,2), size=1, prob =
                                        c((sum(which(pheno$race_3cat==0))/length(pheno$race_3cat)),
                                          (sum(which(pheno$race_3cat==1))/length(pheno$race_3cat)), 
                                          (sum(which(pheno$race_3cat==2))/length(pheno$race_3cat)))), 
                             pheno$race3_imputed) #if not 99, keep the same.

sum(which(pheno$race3_imputed==99)) #we should have no 99s

#now seperate out the categories for model use.
#1 = race = black
#2 = race = nonwhite, nonblack

pheno$race_B <- ifelse(pheno$race3_imputed ==1, 1, 0) #category for this var
pheno$race_NBNW <- ifelse(pheno$race3_imputed ==2, 1, 0) #category for this var

```


```{r breaking up the smoking cat, echo = FALSE}
#for smoking_stat: 
  #0 = never
  #1 =none
  #2 = quit before preg
  #3 = quit during preg (some smoking in preg)
  #4 = smoked during preg
  #6 = not reported
pheno$smoke_Preg <- ifelse(pheno$smoking_stat == 3 | pheno$smoking_stat == 4, 1, 0) #if =3 or 4, 1
pheno$smoke_unknown <- ifelse(pheno$smoking_stat == 6, 1, 0) #if 6, then 1

#checking the work
length(which(pheno$smoking_stat==6)) #9 folks have 6 beofre
sum(pheno$smoke_unknown) #9 folks check in with that cat

print(pheno$smoke_Preg)
sum(pheno$smoke_Preg) #7 have 3 or 4 beofre
length(which(pheno$smoking_stat==3 | pheno$smoking_stat==4)) #and 7 still have the same!
```


```{r formatting our data for models}
exp <- pheno %>% select(starts_with("ln")) #some vars we have numerical, log transformed values

#two vars we have categorical detected or not
exp$MePFOSA_cat <-pheno$MePFOSA_cat
exp$PFUA_cat <- pheno$PFUA_cat

head(exp) #check - looks good!

#let's order things to keep them neat later on: 
expList <- c("PFHxS", "PFOA", "PFOS", "PFNA", "PFDA", "PFUnDA", "MeFOSAA") #keep for table labels
expoOrder <- c("lnPFHxS", "lnPFOA", "lnPFOS", "lnPFNA", "lnPFDeA", "PFUA_cat", "MePFOSA_cat")

exp <- exp[,expoOrder]
head(exp) #good!

#grab the columns that we want
myPhenoCols <- c("Basename","barcode", "Array", "Slide", 
                 "PC1", "PC2", "PC3", "PC4", "PC5", 
                 "Bcell", "CD4T", "CD8T", "Gran","Mono", "NK", "nRBC",
                 "Parity", "race_B", "race_NBNW", "smoke_Preg", "smoke_unknown", 
                 "sex" #remember males=0
                 )

myPheno <- pheno[,myPhenoCols]

dim(exp)
dim(myPheno)
dim(beta)
#sample size stays the same - we should be good to model now. 

#make space on your memory
remove(pheno, expoOrder, myPhenoCols, test)
```

```{r create your model loop and run it}

#simple model: exposure only
#main model: exp + batch (PCx3) + parity + race (2 vars) + smoking (2 vars) + infant sex
#complex model: exp + batch + parity + race + smoking + infant sex + cell types (add 6 to main)

simpleLambdas <- matrix(, nrow=1,ncol=length(exp)) 
mainLambdas <- matrix(, nrow=1,ncol=length(exp))
complexLambdas <- matrix(, nrow=1,ncol=length(exp))

modelSimple <- matrix(, nrow = 0, ncol = 2) #ncol is number of items included in your model + 1 (intercept)
modelMain <- matrix(, nrow = 0, ncol = 11)
modelComplex <- matrix(, nrow = 0, ncol = 18)
modelFinal <- matrix(, nrow = 0, ncol = 16)

for(i in 1:ncol(exp)){
     ##simple model first, just need the lambdas to compare
        simpleDesign<-model.matrix(~exp[,i])
  
        fit<-lmFit(beta, design=simpleDesign, method="ls") #create your regression
        ebfit<-eBayes(fit)#bayesian shrinkage 
        results<-topTable(ebfit,genelist=(annot),number=length(annot@rownames),sort.by="none",adjust="BH",coef=2) 
        simpleLambdas[i]<-P_lambda(results$P.Value)
                
    ##main model next  
        mainDesign<-model.matrix(~exp[,i] + myPheno$PC2 + myPheno$PC3 + myPheno$PC5 +
                                  myPheno$Parity + myPheno$race_B + myPheno$race_NBNW + myPheno$smoke_Preg + myPheno$smoke_unknown +
                                  myPheno$sex)
                                  
        fit<-lmFit(beta, design=mainDesign, method="ls") #create your regression
        ebfit<-eBayes(fit)#bayesian shrinkage 
        #make your summary
        modelsummary<-summary(decideTests(ebfit, method="separate", adjust.method="BH", p.value=0.2,lfc=0))
        modelMain<-rbind(modelMain, modelsummary)
        #pull out results
        results<-topTable(ebfit,genelist=(annot),number=length(annot@rownames),sort.by="none",adjust="BH",coef=2) 
        mainLambdas[i]<-P_lambda(results$P.Value)
        ebfit$SE = (ebfit$sigma*(ebfit$stdev.unscaled[,2])) # add a SE estimate for the effect estimate
        output<-data.frame(results, fit$coefficients[,2],ebfit$SE, check.rows=TRUE) #results
        #write.csv(results, file = paste0(".cpg_model_output/all_cpgs/noncell_model_",exp[,i],"_allresults.csv"))
        
    ##complex model last  
        complexDesign<-model.matrix(~exp[,i] + myPheno$PC2 + myPheno$PC3 + myPheno$PC5 +
                                  myPheno$Parity + myPheno$race_B + myPheno$race_NBNW + myPheno$smoke_Preg + myPheno$smoke_unknown +
                                  myPheno$sex +
                                  myPheno$Bcell + myPheno$CD4T + myPheno$CD8T + myPheno$Gran + myPheno$Mono + myPheno$NK + myPheno$nRBC)
        
        fit<-lmFit(beta, design=complexDesign, method="ls") #create your regression
        ebfit<-eBayes(fit)#bayesian shrinkage 
        #make your summary
        modelsummary<-summary(decideTests(ebfit, method="separate", adjust.method="BH", p.value=0.2,lfc=0))
        modelComplex<-rbind(modelComplex, modelsummary)
        #pull out results
        results<-topTable(ebfit,genelist=(annot),number=length(annot@rownames),sort.by="none",adjust="BH",coef=2) 
        complexLambdas[i]<-P_lambda(results$P.Value)
        ebfit$SE = (ebfit$sigma*(ebfit$stdev.unscaled[,2])) # add a SE estimate for the effect estimate
        output<-data.frame(results, fit$coefficients[,2],ebfit$SE, check.rows=TRUE) #results
        ###write.csv(results, file = paste0("./2.Results_FullModels/MALE_",myphth_names[[i]],"_final_results.csv"))
        
        finalDesign<-model.matrix(~exp[,i] + myPheno$PC2 + myPheno$PC3 + myPheno$PC5 +
                                  myPheno$Parity + myPheno$race_B + myPheno$race_NBNW + 
                                  myPheno$sex +
                                  myPheno$Bcell + myPheno$CD4T + myPheno$CD8T + myPheno$Gran + myPheno$Mono + myPheno$NK + myPheno$nRBC)
        
        fit<-lmFit(beta, design=complexDesign, method="ls") #create your regression
        ebfit<-eBayes(fit)#bayesian shrinkage 
        #make your summary
        modelsummary<-summary(decideTests(ebfit, method="separate", adjust.method="BH", p.value=0.2,lfc=0))
        modelFinal<-rbind(modelFinal, modelsummary)
        #pull out results
        results<-topTable(ebfit,genelist=(annot),number=length(annot@rownames),sort.by="none",adjust="BH",coef=2) 
        complexLambdas[i]<-P_lambda(results$P.Value)
        ebfit$SE = (ebfit$sigma*(ebfit$stdev.unscaled[,2])) # add a SE estimate for the effect estimate
        output<-data.frame(results, fit$coefficients[,2],ebfit$SE, check.rows=TRUE) #results
        #write.csv(results, file = paste0(".cpg_model_output/all_cpgs/final_model_",exp[,i],"_allresults.csv"))
      
        #Identify significant genes at p=0.001 and 0.00001 genes to save for later
        
        subsetloosep<-subset(modelFinal,model$P.Value<0.001) 
        subsetstrictp<-subset(modelFinal,model$P.Value<0.00001)
        #write.csv(subsetloosep, file=paste0(".cpg_model_output/P0.001/final_model_",exp[,i],".csv")) 
        #write.csv(subsetstrictp, file=paste0(".cpg_model_output/P0.00001/final_model_",exp[,i],".csv")) 
}
```


```{r gt tables}
#tables for rmd output were created with the gt package.
```